In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
df = pd.read_csv('train.txt',sep=';',header=None, names=['Text','Emotion'])

In [4]:
df.head()

                                                Text  Emotion
0                            i didnt feel humiliated  sadness
1  i can go from feeling so hopeless to so damned...  sadness
2   im grabbing a minute to post i feel greedy wrong    anger
3  i am ever feeling nostalgic about the fireplac...     love
4                               i am feeling grouchy    anger

In [5]:
df.isnull().sum()

Text       0
Emotion    0
dtype: int64

In [6]:
Emotion_df = df['Emotion'].unique()
Emotion_Number = {}
i=0
for emo in Emotion_df:
    Emotion_Number[emo] = i
    i+=1
df['Emotion']=df['Emotion'].map(Emotion_Number)

In [7]:
df

                                                    Text  Emotion
0                                i didnt feel humiliated        0
1      i can go from feeling so hopeless to so damned...        0
2       im grabbing a minute to post i feel greedy wrong        1
3      i am ever feeling nostalgic about the fireplac...        2
4                                   i am feeling grouchy        1
...                                                  ...      ...
15995  i just had a very brief time in the beanbag an...        0
15996  i am now turning and i feel pathetic that i am...        0
15997                     i feel strong and good overall        5
15998  i feel like this was such a rude comment and i...        1
15999  i know a lot but i feel so stupid because i ca...        0

[16000 rows x 2 columns]

In [8]:
df['Text'] = df['Text'].apply(lambda x : x.lower())

In [9]:
import string

def remove_punc(txt):
    return txt.translate(str.maketrans('','',string.punctuation))

In [10]:
df['Text'] = df['Text'].apply(remove_punc)

In [11]:
def remove_numbers(txt):
    new = ""
    for i in txt:
        if not i.isdigit():
            new = new + i
    return new

In [12]:
df['Text']=df['Text'].apply(remove_numbers)

In [13]:
def remove_emojis(txt):
    new = ""
    for i in txt:
        if i.isascii():
            new = new + i
    return new

In [14]:
df['Text']=df['Text'].apply(remove_emojis)

In [15]:
!pip install nltk

Requirement already satisfied: nltk in c:\users\chava\appdata\roaming\jupyterlab-desktop\envs\env_1\lib\site-packages (3.9.4)
Requirement already satisfied: click in c:\users\chava\appdata\roaming\jupyterlab-desktop\envs\env_1\lib\site-packages (from nltk) (8.4.1)
Requirement already satisfied: joblib in c:\users\chava\appdata\roaming\jupyterlab-desktop\envs\env_1\lib\site-packages (from nltk) (1.5.3)
Requirement already satisfied: regex>=2021.8.3 in c:\users\chava\appdata\roaming\jupyterlab-desktop\envs\env_1\lib\site-packages (from nltk) (2026.5.9)
Requirement already satisfied: tqdm in c:\users\chava\appdata\roaming\jupyterlab-desktop\envs\env_1\lib\site-packages (from nltk) (4.66.5)
Requirement already satisfied: colorama in c:\users\chava\appdata\roaming\jupyterlab-desktop\envs\env_1\lib\site-packages (from click->nltk) (0.4.6)

In [16]:
import nltk

In [17]:
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

In [18]:
nltk.download ('punkt')
nltk.download ('stopwords')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\chava\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\chava\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [19]:
stop_words = set(stopwords.words('english'))

In [20]:
len(stop_words)

198

In [21]:
import nltk
nltk.download('punkt_tab')
nltk.download('stopwords')
nltk.download('wordnet')

[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\chava\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\chava\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\chava\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

True

In [22]:
from nltk.stem import WordNetLemmatizer
lemmatizer = WordNetLemmatizer()
def lemmatize(txt):
    words = word_tokenize(txt.lower())
    lemmatized_words = [lemmatizer.lemmatize(word, pos='v') for word in words]
    return " ".join(lemmatized_words)

In [23]:
df['Text']=df['Text'].apply(lemmatize)

In [24]:
def remove_txt(txt):
    words = word_tokenize(txt)
    cleaned = []
    for i in words:
        if not i in stop_words:
            cleaned.append(i)
    return ' '.join(cleaned)

In [25]:
df['Text'] = df['Text'].apply(remove_txt)

In [26]:
df.loc[1]['Text']

'go feel hopeless damn hopeful around someone care awake'

In [27]:
df.head()

                                                Text  Emotion
0                               didnt feel humiliate        0
1  go feel hopeless damn hopeful around someone c...        0
2              im grab minute post feel greedy wrong        1
3  ever feel nostalgic fireplace know still property        2
4                                       feel grouchy        1

In [28]:
from sklearn.model_selection import train_test_split

X_train,X_test,Y_train,Y_test=train_test_split(
    df['Text'],df['Emotion'],test_size=0.2,random_state=42
)

In [29]:
from sklearn.feature_extraction.text import TfidfVectorizer, CountVectorizer

In [30]:
bow_vectorizer = CountVectorizer()

In [31]:
X_train_bow = bow_vectorizer.fit_transform(X_train)
X_test_bow = bow_vectorizer.transform(X_test)

In [32]:
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score

In [33]:
nb_model = MultinomialNB()

In [34]:
nb_model.fit(X_train_bow,Y_train)

MultinomialNB()

In [35]:
pred_bow = nb_model.predict(X_test_bow)
print(accuracy_score(Y_test,pred_bow))

0.7665625

In [36]:
Y_test

8756     0
4660     5
6095     0
304      5
8241     0
        ..
15578    5
5746     5
6395     5
7624     5
15245    0
Name: Emotion, Length: 3200, dtype: int64

In [37]:
tfidf_vectorizer = TfidfVectorizer(ngram_range=(1, 3),max_features=30000, sublinear_tf=True,min_df=2)

In [38]:
X_train_tfidf = tfidf_vectorizer.fit_transform(X_train)
X_test_tfidf = tfidf_vectorizer.transform(X_test)

In [39]:
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score

In [40]:
nb2_model = MultinomialNB()
nb2_model.fit(X_train_tfidf,Y_train)

MultinomialNB()

In [41]:
pred_tfidf = nb2_model.predict(X_test_tfidf)
print(accuracy_score(Y_test,pred_tfidf))

0.703125

In [42]:
from sklearn.linear_model import LogisticRegression

In [43]:
logistic_model = LogisticRegression(C=10.0,class_weight='balanced',max_iter=1000)

In [44]:
logistic_model.fit(X_train_tfidf,Y_train)

LogisticRegression(C=10.0, class_weight='balanced', max_iter=1000)

In [45]:
log_pred = logistic_model.predict(X_test_tfidf)
print(accuracy_score(Y_test,log_pred))

0.8878125

In [46]:
import pickle

export_data = {
    "vectorizer": tfidf_vectorizer,    
    "model": logistic_model        
}

with open('emotion_assets.pkl', 'wb') as f:
    pickle.dump(export_data, f)

print("Vectorizer and Logistic Regression model saved successfully!")

Vectorizer and Logistic Regression model saved successfully!